version: 1
update_configs:

  - package_manager: submodules
    directory: /
    update_schedule: daily
    commit_message:
      prefix: chore
      include_scope: true
    default_labels:
      - ':recycle: Chore'
